scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout", auth_views.LogoutView.as_view(), name="logout"),
    path("meal_plan/", include("meal_plan.urls")),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagCreateView,
    TagUpdateView,
    TagDetailView,
    TagListView,
    TagDeleteView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tags_detail"),
    path("new/", TagCreateView.as_view(), name="tags_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tags_edit"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tags_delete"),
]

tags/models.py
from django.db import models


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=20)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="tags")

    def __str__(self):
        return self.name

tags/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

# from recipes.forms import RatingForm

# try:
from tags.models import Tag

# except Exception:
#     Tag = None


# Create your views here.
def show_tags(request):
    context = {
        "tags": Tag.objects.all() if Tag else None,
    }
    return render(request, "tags/list.html", context)


class TagListView(ListView):
    model = Tag
    template_name = "tags/list.html"
    paginate_by = 2


class TagDetailView(DetailView):
    model = Tag
    template_name = "tags/detail.html"


class TagCreateView(LoginRequiredMixin, CreateView):
    model = Tag
    template_name = "tags/new.html"
    fields = ["name"]
    success_url = reverse_lazy("tags_list")


class TagUpdateView(LoginRequiredMixin, UpdateView):
    model = Tag
    template_name = "tags/edit.html"
    fields = ["name"]
    success_url = reverse_lazy("tags_list")


class TagDeleteView(LoginRequiredMixin, DeleteView):
    model = Tag
    template_name = "tags/delete.html"
    success_url = reverse_lazy("tags_list")

tags/templates/tags/delete.html
{%extends "base.html" %}

<!DOCTYPE html>
{%block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <p>Are you sure you want to delete this recipe?</p>
    <div class="control">
      <button class="button">Delete</button>
    </div>
  </form>
</main>
{%endblock content %}

tags/templates/tags/detail.html
{%extends "base.html"%} 



<!DOCTYPE html>
{% load markdownify %}
{%block content%}
    <main class="recipe-detail">
      <div>
        <a href="{% url 'tags_edit' tags.id %}">Edit</a>
        <a href="{% url 'tags_delete' tags.id %}">Delete</a>
      </div>
      {% if recipe.image %}
      <img src="{{ tags.image }}" class="pull-right" />
      {% endif %}
      <h1>{{ recipe.name }}</h1>
      <p>{{ recipe.description | markdownify }}</p>
      <p>Created on {{ recipe.created }} | Updated on {{ recipe.updated }}</p>
      <form method="post" action="{% url 'recipe_rating' recipe.id %}">
        {% csrf_token %} {{ rating_form.as_p }}
        <button class="button">Rate</button>
      </form>
      <p>Tags: {% for tag in recipe.tags.all %}{{ tag.word }} {% endfor %}</p>
      <p>{{ recipe.description | markdownify }}</p>
      <h2>Ingredients</h2>
      <table>
        <thead>
          <tr>
            <th colspan="2">Amount</th>
            <th>Food item</th>
          </tr>
        </thead>
        <tbody>
          {% for ingredient in recipe.ingredients.all %}
          <tr>
            <td>{{ ingredient.amount }}</td>
            <td>{{ ingredient.measure.name }}</td>
            <td>{{ ingredient.food.name }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <h2>Steps</h2>
      <ol>
        {% for step in recipe.steps.all %}
        <li>{{ step.directions }}</li>
        {% endfor %}
      </ol>
    </main>
  {% endblock content %}
</html>

tags/templates/tags/edit.html
{%extends "base.html"%}

<!DOCTYPE html>
{%block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{%endblock content%}

tags/templates/tags/list.html
{% extends 'base.html'%} {% block pagination %}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; First</a>
    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
{% endblock pagination %} {% block content %}
<main class="recipe-grid">
  {% for tag in tag_list %}
  <div class="recipe-card">
    <h2 class="recipe-card-title">
      <a href="{% url 'tags_detail' tag.id %}">{{ tag.name }}</a>
    </h2>
    {% for recipe in tag.recipes.all %}
    <p>
      <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
    </p>
    {% endfor %}
  </div>
  {% empty %}
  <div>
    <h1>No tags, yet</h1>
    <p>
      Would you like to
      <a href="{% url 'tags_new' %}">create</a>
      one?
    </p>
  </div>
  {% endfor %}
</main>
{% endblock content %}

tags/templates/tags/new.html
{%extends "base.html"%}

<!DOCTYPE html>
{%block content%}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content%}